<?php
    $nomes = array(
        "Michelle",
        "Iasmin",
        "Valentina",
        "Orquídea",
        "Samantha",
        "Raissa",
        "Benjamim",
        "Angelo",
        "Barbara",
        "Alexandre",
        "Laura",
        "Estêvão",
        "Nayr",
        "Benício",
        "Jennifer",
        "Gastão",
        "Valter",
        "Marina",
        "Lavínia",
        "Vera",
        "Maximiano",
        "Rossana",
        "Dilnura",
        "Michele",
        "Suzi",
        "Giovany",
        "Joana",
        "Anaelle",
        "Mathilde",
        "Jaime",
        "Rayan",
        "Melany",
        "Isac",
        "Alda",
        "Dinarte",
        "Rogério",
        "Cíntia",
        "Kennedy",
        "Kiara",
        "Débora",
        "Jasmine",
        "Louisa",
        "Ilídio",
        "Victoria",
        "Yana",
        "Lavínia",
        "Heloisa",
        "Florinda",
        "Dário",
        "Barbara"
    );
    $nomesN = array_values($nomes);
    $aleatorio = array_rand($nomesN, 1);

    echo $nomesN[$aleatorio];